### ISSUE TITLE
Entity sensor.s10e_additional_total from integration e3dc_rscp has state class total_increasing, but its state is negative.

### ISSUE THREAD

**Issue by derhappy** [torbennehmer/hacs-e3dc#89]
## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.2.0-36-generic
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1339
Downloaded Repositories | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 21
views | 61
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23. August 2023 um 16:23
-- | --
current_recorder_run | 24. November 2023 um 12:19
estimated_db_size | 12965.06 MiB
database_engine | postgresql
database_version | 15.4

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

We have an additional production meter (second PV inverter) which leads to the following error on startup:

Entity sensor.s10e_additional_total from integration e3dc_rscp has state class total_increasing, but its state is negative. Triggered by state -2300.86864 with last_updated set to 2023-11-24T11:14:59.999999+00:00. [...]

Because it's a production sensor it's decreasing. But not all the time, because at night the inverter actually consumes some energy. Maybe just using the absolute value would be a first step. I'm not sure how to proceed with the night issue though.
![grafik](https://github.com/torbennehmer/hacs-e3dc/assets/61394775/514c903b-23ae-4b8a-a0e9-81152f34c701)

### Reproduction steps

Restart HA

### Debug logs

```text
2023-11-24 11:19:03.940 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration e3dc_rscp which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-24 11:19:03.941 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-24 11:19:03.942 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solaredge_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-24 11:19:03.942 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hass_agent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-24 11:19:15.804 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _async_at_core_state.<locals>._matched_event(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/helpers/start.py:37
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 616, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 619, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in _onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 707, in async_run_job
    return self.async_run_hass_job(HassJob(target), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 659, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/start.py", line 40, in _matched_event
    hass.async_run_hass_job(at_start_job, hass)
  File "/usr/src/homeassistant/homeassistant/core.py", line 659, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 478, in _async_template_startup
    result_info.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1031, in async_refresh
    self._refresh(None)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1211, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 659, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 429, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
    raise ValueError(
ValueError: Sensor sensor.position_car has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)
2023-11-24 11:20:10.725 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.s10e_additional_total from integration e3dc_rscp has state class total_increasing, but its state is negative. Triggered by state -2300.86864 with last_updated set to 2023-11-24T11:14:59.999999+00:00. Please create a bug report at https://github.com/torbennehmer/hacs-e3dc/issues
2023-11-24 11:20:58.773 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:20:58.841 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:20:58.850 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:20:58.856 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:20:58.878 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Skipping power metrics poll.
2023-11-24 11:20:58.879 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.105 seconds (success: True)
2023-11-24 11:21:08.773 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:21:08.827 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:21:08.834 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:21:08.839 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:21:08.858 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Skipping power metrics poll.
2023-11-24 11:21:08.858 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.085 seconds (success: True)
2023-11-24 11:21:18.772 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:21:18.826 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:21:18.832 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:21:18.838 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:21:18.855 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling today's power metrics
2023-11-24 11:21:18.855 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Midnight is 2023-11-24 00:00:00+01:00, DB query timestamp is 1700780400, applied offset: 3600
2023-11-24 11:21:18.856 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Midnight DB query timestamp is 1700784000, applied offset: 3600
2023-11-24 11:21:18.882 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.110 seconds (success: True)
2023-11-24 11:21:28.772 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:21:28.829 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:21:28.834 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:21:28.840 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:21:28.859 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Skipping power metrics poll.
2023-11-24 11:21:28.860 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.088 seconds (success: True)
2023-11-24 11:21:38.771 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:21:38.828 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:21:38.834 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:21:38.839 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:21:38.862 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Skipping power metrics poll.
2023-11-24 11:21:38.862 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.090 seconds (success: True)
2023-11-24 11:21:48.771 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:21:48.825 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:21:48.831 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:21:48.837 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:21:48.856 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Skipping power metrics poll.
2023-11-24 11:21:48.856 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.084 seconds (success: True)
2023-11-24 11:21:58.772 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:21:58.829 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:21:58.835 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:21:58.840 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:21:58.858 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Skipping power metrics poll.
2023-11-24 11:21:58.858 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.086 seconds (success: True)
2023-11-24 11:22:08.772 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:22:08.831 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:22:08.837 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:22:08.842 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:22:08.861 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Skipping power metrics poll.
2023-11-24 11:22:08.861 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.089 seconds (success: True)
2023-11-24 11:22:18.771 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:22:18.827 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:22:18.833 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:22:18.838 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:22:18.857 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Skipping power metrics poll.
2023-11-24 11:22:18.857 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.086 seconds (success: True)
2023-11-24 11:22:28.772 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling general status information
2023-11-24 11:22:28.831 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Poll power settings
2023-11-24 11:22:28.840 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling manual charge information
2023-11-24 11:22:28.846 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling additional powermeters
2023-11-24 11:22:28.864 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Polling today's power metrics
2023-11-24 11:22:28.864 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Midnight is 2023-11-24 00:00:00+01:00, DB query timestamp is 1700780400, applied offset: 3600
2023-11-24 11:22:28.864 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Midnight DB query timestamp is 1700784000, applied offset: 3600
2023-11-24 11:22:28.892 DEBUG (MainThread) [custom_components.e3dc_rscp.coordinator] Finished fetching e3dc_rscp data in 0.120 seconds (success: True)
```

### Diagnostics dump

[e3dc_dump.json](https://github.com/torbennehmer/hacs-e3dc/files/13462390/e3dc_dump.json)

**Comment by torbennehmer** [comment]
@derhappy I've worked on improving the auto-detection of the additional powermeters. I'm not entirely sure, how this works out. Would you be able to manually install the current GIT head revision?

**Comment by neuromancer3142** [comment]
I have the same error. See extract from the log:

*** start ***
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:311
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 23. November 2023 um 20:25:55 (3 occurrences)
Last logged: 01:05:12

Entity sensor.s10e_pro_additional_total from integration e3dc_rscp has state class total_increasing, but its state is negative. Triggered by state -2668.92052 with last_updated set to 2023-11-23T19:19:59.999999+00:00. Please create a bug report at https://github.com/torbennehmer/hacs-e3dc/issues
Entity sensor.s10e_pro_root_total from integration e3dc_rscp has state class total_increasing, but its state is negative. Triggered by state -5334.95372 with last_updated set to 2023-11-23T19:19:59.999999+00:00. Please create a bug report at https://github.com/torbennehmer/hacs-e3dc/issues
Entity sensor.s10e_pro_energy_charged_from_grid from integration e3dc_rscp has state class total_increasing, but its state is negative. Triggered by state -0.0001785990625 with last_updated set to 2023-11-25T00:00:08.847498+00:00. Please create a bug report at https://github.com/torbennehmer/hacs-e3dc/issues
*** stop ***

**Comment by torbennehmer** [comment]
Please try the current RC1:
![image](https://github.com/torbennehmer/hacs-e3dc/assets/2812067/5a977f56-8f72-48e2-97d1-efec0c978cf3)
I've just pubished it as a prerelease, so HACS can download it.

If it still fails, please always include Debug Log and the current Diagnostics Dump. If using additional powermeters, please try to take the dump when they show anything. E.g. for an additional inverter, take the dump when it is actually delivering (or draining) anything etc.
